"""empty message

Revision ID: e328f7bf1398
Revises: 7b514ae9d75c
Create Date: 2019-07-04 05:34:12.882486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e328f7bf1398'
down_revision = '7b514ae9d75c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('devicename_dest', sa.String(length=20), nullable=False))
    op.add_column('events', sa.Column('devicename_source', sa.String(length=20), nullable=False))
    op.drop_column('events', 'devicename')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('devicename', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('events', 'devicename_source')
    op.drop_column('events', 'devicename_dest')
    # ### end Alembic commands ###
